name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debugging: List the root directory to see the correct structure
      - name: List directory contents at root
        run: dir

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      # Restore NuGet packages in the correct directory
      - name: Restore NuGet packages
        run: nuget restore CodeWalker\CodeWalker.RPFExplorer\CodeWalker.RPFExplorer.csproj
        working-directory: CodeWalker\CodeWalker.RPFExplorer

      # Build the project in the correct directory
      - name: Build CodeWalker.RPFExplorer project
        run: msbuild CodeWalker\CodeWalker.RPFExplorer\CodeWalker.RPFExplorer.csproj /p:Configuration=Release
        working-directory: CodeWalker\CodeWalker.RPFExplorer

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutput
          path: '**/CodeWalker/CodeWalker.RPFExplorer/bin/Release/*'
