name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # List directory contents to confirm where we are
      - name: List directory contents at root
        run: dir

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      # Explicitly check if the .csproj file exists using absolute paths
      - name: Check if .csproj file exists
        run: |
          echo Checking if .csproj exists
          dir D:\a\CodeWalker\CodeWalker\CodeWalker.RPFExplorer
          dir D:\a\CodeWalker\CodeWalker\CodeWalker.RPFExplorer\CodeWalker.RPFExplorer.csproj

      # Now, restore NuGet packages using absolute path
      - name: Restore NuGet packages with absolute path
        run: |
          nuget restore D:\a\CodeWalker\CodeWalker\CodeWalker.RPFExplorer\CodeWalker.RPFExplorer.csproj
        shell: pwsh

      # Build the project using the absolute path
      - name: Build CodeWalker.RPFExplorer project
        run: |
          msbuild D:\a\CodeWalker\CodeWalker\CodeWalker.RPFExplorer\CodeWalker.RPFExplorer.csproj /p:Configuration=Release
        shell: pwsh

      # Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutput
          path: '**/CodeWalker/CodeWalker.RPFExplorer/bin/Release/*'
