name: Build CodeWalker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build solution
        run: msbuild CodeWalker.sln /p:Configuration=Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutput
          path: |
            **\bin\Release\
